name: Labeler

on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ github.token }}"
          # Whether or not to remove labels when matching files are reverted or no longer changed by the PR
          sync-labels: true # optional, default is false
